"""从 Settings 元数据生成 .env.example。

用法（在 backend/ 目录下）：
    python -m app.shared.env_example          # 重新生成 .env.example
    python -m app.shared.env_example --check  # 校验是否最新（CI 门禁）
"""

import json
import sys

from pydantic_core import PydanticUndefined

from app.shared.config import BASE_DIR, Settings

HEADER = "# Auto-generated by `python -m app.shared.env_example`. Do not edit manually."

# 平台相关的默认值在此覆盖为可移植的示例值
VALUE_OVERRIDES = {
    "database_url": "sqlite+aiosqlite:///./data/app.db",
}


def render() -> str:
    lines = [HEADER]
    for name, field in Settings.model_fields.items():
        if field.description:
            lines.append(f"# {field.description}")
        if name in VALUE_OVERRIDES:
            value = VALUE_OVERRIDES[name]
        elif field.default is PydanticUndefined or field.default is None:
            value = ""
        elif isinstance(field.default, (list, dict)):
            value = json.dumps(field.default, ensure_ascii=False)
        else:
            value = str(field.default)
        lines.append(f"{name.upper()}={value}")
    return "\n".join(lines) + "\n"


def main() -> int:
    target = BASE_DIR / ".env.example"
    content = render()
    if "--check" in sys.argv:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            print("ERROR: .env.example is stale. Regenerate: python -m app.shared.env_example")
            return 1
        print(".env.example is up to date")
        return 0
    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
